Rename app and image
opensafely-core/output-explorer pull request #314
Opened 2022-05-30 15:53 UTC by ghickman

2022-05-30 15:55 UTC, bloodearnest requested changes

2022-05-30 15:55 UTC, bloodearnest commented on .github/workflows/main.yml
> +            ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" dokku@dokku1.ebmdatalab.net git:from-image reports
You need the $SHA here

2022-05-30 15:56 UTC, ghickman commented on .github/workflows/main.yml
> +            ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" dokku@dokku1.ebmdatalab.net git:from-image reports
Oops, thanks!

2022-05-31 08:45 UTC, bloodearnest approved these changes

2022-05-31 08:59 UTC, merged